apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "1k-candidate-verifier.name" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/limit-rps: "10"
    {{ if .Values.certificate.enabled }}
    cert-manager.io/cluster-issuer: letsencrypt
    {{ end }}
spec:
  tls:
  - hosts:
      - {{ .Values.domain }}
    secretName: {{ include "1k-candidate-verifier.tls-secret-name" . }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "1k-candidate-verifier.name" . }}
          servicePort: {{ .Values.api.port }}
